name: Automated release

on:
  push:
    branches-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.2.0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install vpk

      - name: Publish mod VPK
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: |
          git fetch
          chmod +x gradlew
          ./gradlew clean run --args=publish
          
      - name: Upload VPK
        uses: actions/upload-artifact@v2
        with:
          path: |
            pak01_dir.vpk
            pak01_dir.vpk.sha512
